spring:
  server:
    port: ${SERVER_PORT:8080}
  datasource:
    url: ${DB_URL:jdbc:mariadb://localhost:3306/springapiliquibasedb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: ${DB_DRIVER:org.mariadb.jdbc.Driver}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
